name: "deploy"

on:
  push:
    branches:
      - m1-test


jobs:
  build_tauri:
    timeout-minutes: 6
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
          # - os: macos-11
          #   name: darwin+x86-64
          # - os: ubuntu-latest
          #   name: linux+x86-64
          - os: [self-hosted, macOS, ARM64]
            name: darwin+aarch64
          # - os: [self-hosted, linux, ARM64]
          #   name: linux+aarch64
    container: ${{ matrix.platform.container }}
    steps:
    - uses: actions/checkout@v2

    - uses: pnpm/action-setup@v2
      with:
        version: 7
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 18
        cache: 'pnpm'
        cache-dependency-path: pnpm-lock.yaml
    - name: install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: Swatinem/rust-cache@v2
      with:
        # The prefix cache key, this can be changed to start a new cache manually.
        # default: "v0-rust"
        prefix-key: ${{ matrix.platform.name }}
        shared-key: prod
        cache-targets: false
    # - name: install dependencies (ubuntu only)
    #   if: matrix.platform.name == 'linux+x86-64'
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
    - name: install app dependencies
      run: pnpm install

    - name: Cache Tauri Target
      uses: actions/cache@v3
      with:
        path: |
          ./modules/gui/src-tauri/target
        key: m1-test
        restore-keys: m1-test

    - name: test dev tauri
      run: pnpm build:gui

    - name: zip app
      run: zip -r tea.zip ./modules/gui/src-tauri/target/release/bundle/macos/tea.app

    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: cp package images from prod to preview bucket
      run: |
        aws s3 cp ./tea.zip "s3://preview.gui.tea.xyz/release/tea.zip"