name: "deploy"

on:
  push:
    branches:
      - m1-test


jobs:
  build_tauri:
    timeout-minutes: 6
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
          # - os: macos-11
          #   name: darwin+x86-64
          # - os: ubuntu-latest
          #   name: linux+x86-64
          - os: [self-hosted, macOS, ARM64]
            name: darwin+aarch64
          # - os: [self-hosted, linux, ARM64]
          #   name: linux+aarch64
    container: ${{ matrix.platform.container }}
    steps:
    - uses: actions/checkout@v2

    # - uses: teaxyz/setup@v0
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     ENABLE_CODE_SIGNING: ${{ secrets.APPLE_CERTIFICATE_P12 }}
    #     APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE_P12 }}
    #     APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_P12_PASSWORD }}
    #     APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
    #     APPLE_ID: ${{ secrets.APPLE_ID }}
    #     APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
    #   with:
    #     target: build

    # - name: zip app
    #   run: |
    #     cd ./modules/gui/src-tauri/target/release/bundle/macos/ && zip -r tea.zip tea.app

    # - uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: us-east-1

    # - name: cp package images from prod to preview bucket
    #   run: |
    #     aws s3 cp ./modules/gui/src-tauri/target/release/bundle/macos/tea.zip "s3://preview.gui.tea.xyz/release/tea.zip"
    - name: setup node
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: pnpm/action-setup@v2
      with:
        version: 7.18.2
        run_install: true
  
    # - uses: apple-actions/import-codesign-certs@d54750db52a4d3eaed0fc107a8bab3958f3f7494
    #   with:
    #     p12-file-base64: ${{ secrets.APPLE_CERTIFICATE_P12 }}
    #     p12-password: ${{ secrets.APPLE_CERTIFICATE_P12_PASSWORD }}
    - run: pnpm build:gui

    - name: Codesign package
      run: |
        codesign -s "Developer ID Application: Tea Inc. (7WV56FL599)" -v --force --deep --timestamp --preserve-metadata=entitlements -o runtime ./modules/gui/src-tauri/target/release/bundle/macos/tea.app || true
        done

    - name: zip app
      run: |
        cd ./modules/gui/src-tauri/target/release/bundle/macos/ && zip -r tea.zip tea.app

    - name: cp package images from prod to preview bucket
      run: |
        aws s3 cp ./modules/gui/src-tauri/target/release/bundle/macos/tea.zip "s3://preview.gui.tea.xyz/release/tea.zip"